config/routes.rb
Rails.application.routes.draw do

resources :posts

  get 'home/index'
  root 'posts#index'

  devise_for :users

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  acts_as_votable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order("created_at DESC")
    @post = Post.new
  end

  def new
    @post = Post.new
  end

  def create

    post = Post.new(post_params)
    if post.save
      flash[:msg]= "post created"
    else
      flash[:msg]= "post failed"
    end
    redirect_to posts_path
  end

  def update
    post = Post.find(params[:id])
    if post.update(post_params)
      flash[:msg]= "post created"
    else
      flash[:msg]= "post failed"
    end
    redirect_to root_path
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    post = Post.find(params[:id])
    if post.destroy(post_params)
      flash[:msg]= "post deleted"
    else
      flash[:msg]= "cant delete this post"
    end
    redirect_to root_path
  end

  def edit
  end

  private

  def post_params
    params.require(:post).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Exp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href=<%= home_index_path%>>
          <img alt="Brand" src="...">
        </a>
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
        <!-- <button type="button" class="btn btn-default navbar-btn">Sign in</button> -->
      </div>
    </div>
  </nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div class="container">
    <%= yield %>
  </div>

<p class="navbar-text pull-right">

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f|%>
  <div class="form-group">
    <%= f.label :title%>
    <%= f.text_field :title%>
  </div>
  <div class="form-group">
    <%= f.label :description%>
    <%= f.text_field :description%>
  </div>
  <div class="form-group">
    <%= f.submit%>
  </div>

<%end%>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<% if user_signed_in? %>
  <%= link_to "new post", new_post_path, class: "glyphicon glyphicon-plus btn btn-danger " %>
  <%= render "form"%>
<%else%>
  <p class = 'alert alert-success'>
    Sign in to add post or comment
  </p>
<%end%>

<% @posts.each do |post|%>
<div class = "post">
 <h2><%= post.title%><br></h2>
  <%= post.description%><br>
</div>

<%end%>

app/views/posts/new.html.erb
<%= form_for @post do |f|%>
  <div class="form-group">
    <%= f.label :title%>
    <%= f.text_field :title%>
  </div>
  <div class="form-group">
    <%= f.label :description%>
    <%= f.text_field :description%>
  </div>
  <div class="form-group">
    <%= f.submit%>
  </div>

<%end%>

app/views/posts/show.html.erb
<%= @post.title%>
<%=@post.description%>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>